
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Iklan` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Iklan
 * 
 */
export type IklanModel = runtime.Types.Result.DefaultSelection<Prisma.$IklanPayload>

export type AggregateIklan = {
  _count: IklanCountAggregateOutputType | null
  _avg: IklanAvgAggregateOutputType | null
  _sum: IklanSumAggregateOutputType | null
  _min: IklanMinAggregateOutputType | null
  _max: IklanMaxAggregateOutputType | null
}

export type IklanAvgAggregateOutputType = {
  id: number | null
}

export type IklanSumAggregateOutputType = {
  id: number | null
}

export type IklanMinAggregateOutputType = {
  id: number | null
  judul: string | null
  link: string | null
}

export type IklanMaxAggregateOutputType = {
  id: number | null
  judul: string | null
  link: string | null
}

export type IklanCountAggregateOutputType = {
  id: number
  judul: number
  link: number
  _all: number
}


export type IklanAvgAggregateInputType = {
  id?: true
}

export type IklanSumAggregateInputType = {
  id?: true
}

export type IklanMinAggregateInputType = {
  id?: true
  judul?: true
  link?: true
}

export type IklanMaxAggregateInputType = {
  id?: true
  judul?: true
  link?: true
}

export type IklanCountAggregateInputType = {
  id?: true
  judul?: true
  link?: true
  _all?: true
}

export type IklanAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Iklan to aggregate.
   */
  where?: Prisma.IklanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iklans to fetch.
   */
  orderBy?: Prisma.IklanOrderByWithRelationInput | Prisma.IklanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IklanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iklans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iklans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Iklans
  **/
  _count?: true | IklanCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IklanAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IklanSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IklanMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IklanMaxAggregateInputType
}

export type GetIklanAggregateType<T extends IklanAggregateArgs> = {
      [P in keyof T & keyof AggregateIklan]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIklan[P]>
    : Prisma.GetScalarType<T[P], AggregateIklan[P]>
}




export type IklanGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IklanWhereInput
  orderBy?: Prisma.IklanOrderByWithAggregationInput | Prisma.IklanOrderByWithAggregationInput[]
  by: Prisma.IklanScalarFieldEnum[] | Prisma.IklanScalarFieldEnum
  having?: Prisma.IklanScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IklanCountAggregateInputType | true
  _avg?: IklanAvgAggregateInputType
  _sum?: IklanSumAggregateInputType
  _min?: IklanMinAggregateInputType
  _max?: IklanMaxAggregateInputType
}

export type IklanGroupByOutputType = {
  id: number
  judul: string
  link: string
  _count: IklanCountAggregateOutputType | null
  _avg: IklanAvgAggregateOutputType | null
  _sum: IklanSumAggregateOutputType | null
  _min: IklanMinAggregateOutputType | null
  _max: IklanMaxAggregateOutputType | null
}

export type GetIklanGroupByPayload<T extends IklanGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IklanGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IklanGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IklanGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IklanGroupByOutputType[P]>
      }
    >
  >



export type IklanWhereInput = {
  AND?: Prisma.IklanWhereInput | Prisma.IklanWhereInput[]
  OR?: Prisma.IklanWhereInput[]
  NOT?: Prisma.IklanWhereInput | Prisma.IklanWhereInput[]
  id?: Prisma.IntFilter<"Iklan"> | number
  judul?: Prisma.StringFilter<"Iklan"> | string
  link?: Prisma.StringFilter<"Iklan"> | string
}

export type IklanOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  judul?: Prisma.SortOrder
  link?: Prisma.SortOrder
}

export type IklanWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.IklanWhereInput | Prisma.IklanWhereInput[]
  OR?: Prisma.IklanWhereInput[]
  NOT?: Prisma.IklanWhereInput | Prisma.IklanWhereInput[]
  judul?: Prisma.StringFilter<"Iklan"> | string
  link?: Prisma.StringFilter<"Iklan"> | string
}, "id">

export type IklanOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  judul?: Prisma.SortOrder
  link?: Prisma.SortOrder
  _count?: Prisma.IklanCountOrderByAggregateInput
  _avg?: Prisma.IklanAvgOrderByAggregateInput
  _max?: Prisma.IklanMaxOrderByAggregateInput
  _min?: Prisma.IklanMinOrderByAggregateInput
  _sum?: Prisma.IklanSumOrderByAggregateInput
}

export type IklanScalarWhereWithAggregatesInput = {
  AND?: Prisma.IklanScalarWhereWithAggregatesInput | Prisma.IklanScalarWhereWithAggregatesInput[]
  OR?: Prisma.IklanScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IklanScalarWhereWithAggregatesInput | Prisma.IklanScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Iklan"> | number
  judul?: Prisma.StringWithAggregatesFilter<"Iklan"> | string
  link?: Prisma.StringWithAggregatesFilter<"Iklan"> | string
}

export type IklanCreateInput = {
  judul: string
  link: string
}

export type IklanUncheckedCreateInput = {
  id?: number
  judul: string
  link: string
}

export type IklanUpdateInput = {
  judul?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IklanUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  judul?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IklanCreateManyInput = {
  id?: number
  judul: string
  link: string
}

export type IklanUpdateManyMutationInput = {
  judul?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IklanUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  judul?: Prisma.StringFieldUpdateOperationsInput | string
  link?: Prisma.StringFieldUpdateOperationsInput | string
}

export type IklanCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  judul?: Prisma.SortOrder
  link?: Prisma.SortOrder
}

export type IklanAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IklanMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  judul?: Prisma.SortOrder
  link?: Prisma.SortOrder
}

export type IklanMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  judul?: Prisma.SortOrder
  link?: Prisma.SortOrder
}

export type IklanSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type IklanSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  judul?: boolean
  link?: boolean
}, ExtArgs["result"]["iklan"]>

export type IklanSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  judul?: boolean
  link?: boolean
}, ExtArgs["result"]["iklan"]>

export type IklanSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  judul?: boolean
  link?: boolean
}, ExtArgs["result"]["iklan"]>

export type IklanSelectScalar = {
  id?: boolean
  judul?: boolean
  link?: boolean
}

export type IklanOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "judul" | "link", ExtArgs["result"]["iklan"]>

export type $IklanPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Iklan"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    judul: string
    link: string
  }, ExtArgs["result"]["iklan"]>
  composites: {}
}

export type IklanGetPayload<S extends boolean | null | undefined | IklanDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IklanPayload, S>

export type IklanCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IklanFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IklanCountAggregateInputType | true
  }

export interface IklanDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Iklan'], meta: { name: 'Iklan' } }
  /**
   * Find zero or one Iklan that matches the filter.
   * @param {IklanFindUniqueArgs} args - Arguments to find a Iklan
   * @example
   * // Get one Iklan
   * const iklan = await prisma.iklan.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IklanFindUniqueArgs>(args: Prisma.SelectSubset<T, IklanFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Iklan that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IklanFindUniqueOrThrowArgs} args - Arguments to find a Iklan
   * @example
   * // Get one Iklan
   * const iklan = await prisma.iklan.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IklanFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IklanFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Iklan that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanFindFirstArgs} args - Arguments to find a Iklan
   * @example
   * // Get one Iklan
   * const iklan = await prisma.iklan.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IklanFindFirstArgs>(args?: Prisma.SelectSubset<T, IklanFindFirstArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Iklan that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanFindFirstOrThrowArgs} args - Arguments to find a Iklan
   * @example
   * // Get one Iklan
   * const iklan = await prisma.iklan.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IklanFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IklanFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Iklans that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Iklans
   * const iklans = await prisma.iklan.findMany()
   * 
   * // Get first 10 Iklans
   * const iklans = await prisma.iklan.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const iklanWithIdOnly = await prisma.iklan.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IklanFindManyArgs>(args?: Prisma.SelectSubset<T, IklanFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Iklan.
   * @param {IklanCreateArgs} args - Arguments to create a Iklan.
   * @example
   * // Create one Iklan
   * const Iklan = await prisma.iklan.create({
   *   data: {
   *     // ... data to create a Iklan
   *   }
   * })
   * 
   */
  create<T extends IklanCreateArgs>(args: Prisma.SelectSubset<T, IklanCreateArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Iklans.
   * @param {IklanCreateManyArgs} args - Arguments to create many Iklans.
   * @example
   * // Create many Iklans
   * const iklan = await prisma.iklan.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IklanCreateManyArgs>(args?: Prisma.SelectSubset<T, IklanCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Iklans and returns the data saved in the database.
   * @param {IklanCreateManyAndReturnArgs} args - Arguments to create many Iklans.
   * @example
   * // Create many Iklans
   * const iklan = await prisma.iklan.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Iklans and only return the `id`
   * const iklanWithIdOnly = await prisma.iklan.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IklanCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IklanCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Iklan.
   * @param {IklanDeleteArgs} args - Arguments to delete one Iklan.
   * @example
   * // Delete one Iklan
   * const Iklan = await prisma.iklan.delete({
   *   where: {
   *     // ... filter to delete one Iklan
   *   }
   * })
   * 
   */
  delete<T extends IklanDeleteArgs>(args: Prisma.SelectSubset<T, IklanDeleteArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Iklan.
   * @param {IklanUpdateArgs} args - Arguments to update one Iklan.
   * @example
   * // Update one Iklan
   * const iklan = await prisma.iklan.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IklanUpdateArgs>(args: Prisma.SelectSubset<T, IklanUpdateArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Iklans.
   * @param {IklanDeleteManyArgs} args - Arguments to filter Iklans to delete.
   * @example
   * // Delete a few Iklans
   * const { count } = await prisma.iklan.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IklanDeleteManyArgs>(args?: Prisma.SelectSubset<T, IklanDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Iklans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Iklans
   * const iklan = await prisma.iklan.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IklanUpdateManyArgs>(args: Prisma.SelectSubset<T, IklanUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Iklans and returns the data updated in the database.
   * @param {IklanUpdateManyAndReturnArgs} args - Arguments to update many Iklans.
   * @example
   * // Update many Iklans
   * const iklan = await prisma.iklan.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Iklans and only return the `id`
   * const iklanWithIdOnly = await prisma.iklan.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IklanUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IklanUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Iklan.
   * @param {IklanUpsertArgs} args - Arguments to update or create a Iklan.
   * @example
   * // Update or create a Iklan
   * const iklan = await prisma.iklan.upsert({
   *   create: {
   *     // ... data to create a Iklan
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Iklan we want to update
   *   }
   * })
   */
  upsert<T extends IklanUpsertArgs>(args: Prisma.SelectSubset<T, IklanUpsertArgs<ExtArgs>>): Prisma.Prisma__IklanClient<runtime.Types.Result.GetResult<Prisma.$IklanPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Iklans.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanCountArgs} args - Arguments to filter Iklans to count.
   * @example
   * // Count the number of Iklans
   * const count = await prisma.iklan.count({
   *   where: {
   *     // ... the filter for the Iklans we want to count
   *   }
   * })
  **/
  count<T extends IklanCountArgs>(
    args?: Prisma.Subset<T, IklanCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IklanCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Iklan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IklanAggregateArgs>(args: Prisma.Subset<T, IklanAggregateArgs>): Prisma.PrismaPromise<GetIklanAggregateType<T>>

  /**
   * Group by Iklan.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IklanGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IklanGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IklanGroupByArgs['orderBy'] }
      : { orderBy?: IklanGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IklanGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIklanGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Iklan model
 */
readonly fields: IklanFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Iklan.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IklanClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Iklan model
 */
export interface IklanFieldRefs {
  readonly id: Prisma.FieldRef<"Iklan", 'Int'>
  readonly judul: Prisma.FieldRef<"Iklan", 'String'>
  readonly link: Prisma.FieldRef<"Iklan", 'String'>
}
    

// Custom InputTypes
/**
 * Iklan findUnique
 */
export type IklanFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter, which Iklan to fetch.
   */
  where: Prisma.IklanWhereUniqueInput
}

/**
 * Iklan findUniqueOrThrow
 */
export type IklanFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter, which Iklan to fetch.
   */
  where: Prisma.IklanWhereUniqueInput
}

/**
 * Iklan findFirst
 */
export type IklanFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter, which Iklan to fetch.
   */
  where?: Prisma.IklanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iklans to fetch.
   */
  orderBy?: Prisma.IklanOrderByWithRelationInput | Prisma.IklanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Iklans.
   */
  cursor?: Prisma.IklanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iklans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iklans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iklans.
   */
  distinct?: Prisma.IklanScalarFieldEnum | Prisma.IklanScalarFieldEnum[]
}

/**
 * Iklan findFirstOrThrow
 */
export type IklanFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter, which Iklan to fetch.
   */
  where?: Prisma.IklanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iklans to fetch.
   */
  orderBy?: Prisma.IklanOrderByWithRelationInput | Prisma.IklanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Iklans.
   */
  cursor?: Prisma.IklanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iklans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iklans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iklans.
   */
  distinct?: Prisma.IklanScalarFieldEnum | Prisma.IklanScalarFieldEnum[]
}

/**
 * Iklan findMany
 */
export type IklanFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter, which Iklans to fetch.
   */
  where?: Prisma.IklanWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Iklans to fetch.
   */
  orderBy?: Prisma.IklanOrderByWithRelationInput | Prisma.IklanOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Iklans.
   */
  cursor?: Prisma.IklanWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Iklans from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Iklans.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Iklans.
   */
  distinct?: Prisma.IklanScalarFieldEnum | Prisma.IklanScalarFieldEnum[]
}

/**
 * Iklan create
 */
export type IklanCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * The data needed to create a Iklan.
   */
  data: Prisma.XOR<Prisma.IklanCreateInput, Prisma.IklanUncheckedCreateInput>
}

/**
 * Iklan createMany
 */
export type IklanCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Iklans.
   */
  data: Prisma.IklanCreateManyInput | Prisma.IklanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Iklan createManyAndReturn
 */
export type IklanCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * The data used to create many Iklans.
   */
  data: Prisma.IklanCreateManyInput | Prisma.IklanCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Iklan update
 */
export type IklanUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * The data needed to update a Iklan.
   */
  data: Prisma.XOR<Prisma.IklanUpdateInput, Prisma.IklanUncheckedUpdateInput>
  /**
   * Choose, which Iklan to update.
   */
  where: Prisma.IklanWhereUniqueInput
}

/**
 * Iklan updateMany
 */
export type IklanUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Iklans.
   */
  data: Prisma.XOR<Prisma.IklanUpdateManyMutationInput, Prisma.IklanUncheckedUpdateManyInput>
  /**
   * Filter which Iklans to update
   */
  where?: Prisma.IklanWhereInput
  /**
   * Limit how many Iklans to update.
   */
  limit?: number
}

/**
 * Iklan updateManyAndReturn
 */
export type IklanUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * The data used to update Iklans.
   */
  data: Prisma.XOR<Prisma.IklanUpdateManyMutationInput, Prisma.IklanUncheckedUpdateManyInput>
  /**
   * Filter which Iklans to update
   */
  where?: Prisma.IklanWhereInput
  /**
   * Limit how many Iklans to update.
   */
  limit?: number
}

/**
 * Iklan upsert
 */
export type IklanUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * The filter to search for the Iklan to update in case it exists.
   */
  where: Prisma.IklanWhereUniqueInput
  /**
   * In case the Iklan found by the `where` argument doesn't exist, create a new Iklan with this data.
   */
  create: Prisma.XOR<Prisma.IklanCreateInput, Prisma.IklanUncheckedCreateInput>
  /**
   * In case the Iklan was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IklanUpdateInput, Prisma.IklanUncheckedUpdateInput>
}

/**
 * Iklan delete
 */
export type IklanDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
  /**
   * Filter which Iklan to delete.
   */
  where: Prisma.IklanWhereUniqueInput
}

/**
 * Iklan deleteMany
 */
export type IklanDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Iklans to delete
   */
  where?: Prisma.IklanWhereInput
  /**
   * Limit how many Iklans to delete.
   */
  limit?: number
}

/**
 * Iklan without action
 */
export type IklanDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Iklan
   */
  select?: Prisma.IklanSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Iklan
   */
  omit?: Prisma.IklanOmit<ExtArgs> | null
}
